# Generated by Django 5.0.6 on 2024-07-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('userid', models.CharField(max_length=10, unique=True)),
                ('Email', models.EmailField(max_length=254)),
                ('phone_no', models.IntegerField(unique=True)),
                ('passwords', models.CharField(max_length=120)),
                ('moneybox', models.IntegerField(blank=True, null=True)),
                ('depost', models.IntegerField(blank=True, null=True)),
                ('withdrawls', models.IntegerField(blank=True, null=True)),
                ('historys', models.TextField(blank=True, null=True)),
                ('timestraps', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
